### PR TITLE
Support  longdouble data types

### PR DESCRIPTION
**Pull request by aarchiba**
The goal is to have emcee work with coordinates that are numpy long doubles (80-bit precision on most Intel, 128-bit on arm64, 64-bit on MSVC). It's not essential that affine combinations permit long doubles as coefficients; the concern is when the clump of walkers is in a small region around some large-ish long double value. This comes up when fitting times in pulsar data.

### CODE REVIEW

**Comment by aarchiba** [comment]
Current state is, as far as I can tell, that somewhere the HDF5 backend eats the extra precision. I was planning to write a series of backend tests that walk through opening, creating a new dataset, adding things, closing, and reopening, and at each step checking data types, both returned and in the HDF5 file.

**Comment by aarchiba** [comment]
Addresses #312

**Comment by dfm** [comment]
So it looks like most of the errors are actually coming from the linear dependence check. Note that `cond` doesn't exist in `scipy.linalg` so it'll take a bit more tweaking to get that to work. Perhaps we should just skip the check if the dtype isn't `float32` or `float64`?

Also: I recently rearranged the repo a bit to put all the code in a `src` directory. Could you merge the current master and move the new tests to `src/emcee/tests/unit` instead of `emcee/tests/integration`?

**Comment by aarchiba** [comment]
I did the merge but forgot to move the new test file. I'll do that.

**Comment by aarchiba** [comment]
The errors coming from the check are easy to fix or ignore. I'm afraid the more serious error may have gotten lost in the merging, I'll try to surface it again, but:

with a default backend, long doubles actually  work as long as you pass in dtype=np.longdouble.

With the HDF5 backend, long doubles appear to work but the extra precision is lost somewhere, even though no exception is raised and I create all datasets with a dtype of np.longdouble.

**Comment by aarchiba** [comment]
Well. There's an unfortunate partial explanation: HDF5 has no portable IEEE 80-bit float type. No portable floating-point type with more than 64 bits at all. The standard does permit native long doubles, but I'm not sure of the status of h5py's support. I'll look into this.

**Comment by aarchiba** [comment]
Am I mistaken or did you blacken the source code? That is, can I just run black willy-nilly and stop worrying about formatting?

**Comment by dfm** [comment]
Yes I did! The only custom configuration is [the line length defined here](https://github.com/dfm/emcee/blob/master/pyproject.toml#L5) but black should find that automatically!

**Comment by aarchiba** [comment]
Nothing so grand I just forgot to pass dtype from the temporary HDF5 thing to the actual one.

Is it worth warning users that the generated HDF5 files are non-portable if they contain long doubles? In particular arm64 has quadruple precision long doubles. (Travis sort of supports this architecture now, if you want to add tests; on Windows long double is the same as double, so funny things can happen there too, but I think my code is fine if pointless there.)

I don't support complex values, and I use 64-bit floats for the condition number - but I added a normalization step which should help everyone.

**Comment by aarchiba** [comment]
> Yes I did! The only custom configuration is [the line length defined here](https://github.com/dfm/emcee/blob/master/pyproject.toml#L5) but black should find that automatically!

Very nice! I just did that to PINT, which has the usual problem of being written by expert scientists who are not expert programmers. I added a pre-commit hook and a Travis job to check continued blackness: https://github.com/nanograv/PINT/commit/ef448d5271e7ce4a2de912dd2a76a629e7a569cb and also later a hack so that modern git blame will ignore the blackening commit: https://github.com/nanograv/PINT/commit/12ea9cca3d26be549807259cd325ef31d678d3f2 plus documentation on how to set up your environment to use these: https://nanograv-pint.readthedocs.io/en/latest/development-setup.html#command-line-tools-and-automation

**Comment by dfm** [comment]
Very nice! If you have ipynbs, I made a project to enable black for them as a check or git hook: https://github.com/dfm/black_nbconvert

I'm using that for [my current main project](https://github.com/dfm/exoplanet/blob/master/.github/workflows/codestyle.yml), but I don't have any developer docs yet...

**Comment by aarchiba** [comment]
We are using [jupytext](https://github.com/mwouts/jupytext) to manage our notebooks in git - only markdown versions with no output are stored, so diffing and merging is easy. Then [nbsphinx](https://nbsphinx.readthedocs.io/en/0.4.3/) runs and renders them into our online docs, and `jupytext --pipe black --pipe-format py:percent` handles blackening.

**Comment by aarchiba** [comment]
It might have gotten lost in the conversation but: it appears that long doubles now work.

**Comment by aarchiba** [comment]
Would you be interested in a Travis job on arm64, where long double is binary128 (quad precision)? I have astropy building and passing the test suite but arm64 is still a bit experimental and slow. (I don't currently have access to an arm64 machine for testing.)

**Comment by dfm** [comment]
Thanks for this!

**Pull request merged**
