### PR TITLE
fix norm of zero

### PR DESCRIPTION
**Pull request by gboehl**
If `s[i]` and `z` are the same, `norm = 0` which results in `NaNs`. The fix is trivial.

### CODE REVIEW

**Comment by dfm** [comment]
Thanks for the contribution.

Unfortunately this is not a good solution for two reasons:

1. Asking a truthy question about a float is not a good idea (using something like `np.allclose` would be better).
2. If `s[i] == z` then something else is going wrong (probably an initialization issue!) because different walkers shouldn't ever have identical coordinates.

Can you post some sample code that hits this issue so that we can understand what's going on?

Thanks.

**Comment by gboehl** [comment]
Thanks for looking into this! I admit that this is a quite ad-hoc fix. To your comments:

I think the truthy question here is okay as I really only wanted to capture the `s[i]==z` case. But of course you are right that this actually shouldn't happen.

Unfortunately I can't post an example. This only happend once in a large scale estimation where the initial values are drawn from the prior distribution. So the problem probably lies there :)

**Comment by gboehl** [comment]
You were right, there was a bug in the sampler from the prior. Thanks for pointing me to the right place!

**Comment by gboehl** [comment]
And many thanks for providing this package! It is extremely useful and very well done!

**Comment by dfm** [comment]
Awesome! Glad you tracked it down. It might be worth adding a check that handles this case more gracefully, but we'll have to think a bit about how to implement that.

**Pull request closed without merging**
