### PR TITLE
Fix long double test failures with HDF5 and ppc64el

### LINKED ISSUE #353: long double tests fail on ppc64el
**General information:**

- emcee version: 3.0.2
- platform: ppc64el
- installation method (pip/conda/source/other?): Ubuntu/Debian package

**Problem description:**

Version 3.0.2 of emcee is not migrating to the release pocket of Ubuntu because tests are failing on ppc64el: https://autopkgtest.ubuntu.com/packages/e/emcee/groovy/ppc64el

### Expected behavior

tests pass

### Actual behavior: 

test_longdouble_actually_needed[TempHDFBackend] and test_longdouble_preserved[TempHDFBackend] fail:

```
_______________ test_longdouble_actually_needed[TempHDFBackend] ________________

cls = <class 'emcee.backends.hdf.TempHDFBackend'>

    @pytest.mark.parametrize("cls", [emcee.backends.Backend,
                                     emcee.backends.TempHDFBackend])
    def test_longdouble_actually_needed(cls):
    
        mjd = np.longdouble(58000.)
        sigma = 100*np.finfo(np.longdouble).eps*mjd
    
        def log_prob(x):
            assert x.dtype == np.longdouble
            return -0.5 * np.sum(((x-mjd)/sigma) ** 2)
    
        ndim, nwalkers = 1, 20
        steps = 1000
        p0 = sigma*np.random.randn(nwalkers, ndim).astype(np.longdouble) + mjd
        assert not all(p0 == mjd)
    
        with cls(dtype=np.longdouble) as backend:
            sampler = emcee.EnsembleSampler(nwalkers,
                                            ndim,
                                            log_prob,
                                            backend=backend)
            sampler.run_mcmc(p0, steps)
    
            samples = sampler.get_chain().reshape((-1,))
>           assert samples.dtype == np.longdouble
E           AssertionError: assert dtype('<f8') == <class 'numpy.float128'>
E            +  where dtype('<f8') = array([ 5.80000000e+04, -4.60105223e-27,  5.80000000e+04, ...,\n       -6.24580733e-26,  5.80000000e+04, -7.38930048e-27]).dtype
E            +  and   <class 'numpy.float128'> = np.longdouble
```

(the other failure is similar)

### What have you tried so far?

Googling and getting a headache :)

I know that "long double" on PowerPC / POWER is a strange pair-of-64-bit-doubles type so I'm not surprised that it's on POWER that I see the problem. I also see from searching that hd5/h5py/numpy have a history of problems in this area (e.g. https://github.com/h5py/h5py/issues/817) so I'm not sure what the resolution should be. Skipping these tests on ppc64el for now (maybe in an Ubuntu specific patch) might make sense -- it's not like the failure of these new tests indicates any kind of regression.

### PR DESCRIPTION
**Pull request by aarchiba**
Detects whether HDF5 supports long doubles and `xfail`s tests if it doesn't.

Closes #353

### CODE REVIEW

**Comment by aarchiba** [comment]
Er, I'm a little confused - @dfm it looks like `main` is now the default branch but `master` has newer commits? I misunderstood and based this on `master`.

**Comment by aarchiba** [comment]
Partially addresses #356 (only `h5py` not `scipy`)

**Comment by dfm** [comment]
Re: `main` branch: Sorry - yes! I've merged `master` and we should work on `main`. Thanks!

**Comment by dfm** [comment]
This is great - thanks!!

**Pull request merged**
