### PR TITLE
CI: Test on python 3.4 and 3.5. Add coverage.

### PR DESCRIPTION
**Pull request by ericdill**
Commit 1 adds testing for python 3.4 and 3.5 to travis-ci.

Commit 2 collects coverage stats for the test suite, uses codecov to parse and
render the output and adds a badge from codecov to the readme.  Happy to remove
the second commit if you would like.

### CODE REVIEW

**Comment by ericdill** [comment]
Oh, I can also add nightly python testing if you want, though that seems slight overkill

**Comment by ericdill** [comment]
Apparently the coverage module is not python 3.2 compatible.  Would you like to

1. Don't gather coverage stats and thus don't need to worry about this error
2. Skip gathering of coverage stats for python 3.2 only
3. Drop python 3.2 support from CI

**Comment by dfm** [comment]
I'd be happy to drop Py3.2. Thanks for this!

**Comment by ericdill** [comment]
bump @dfm

**Comment by dfm** [comment]
Thanks!

**Pull request merged**
