### PR TITLE
MAINT: fixes gh226, gh182

### PR DESCRIPTION
**Pull request by andyfaff**
EnsembleSampler.sample raises an IndexError if `iterations` is not a multiple of `thin`. This PR fixes that and adds a test for the bug.

### CODE REVIEW

**Comment by dfm** [comment]
Thanks! Sorry for the delay - I was on holiday.

Can you remove the scipy dependency from the test?

**Comment by andyfaff** [comment]
Dependency removed. Let's see if this works

**Comment by andyfaff** [comment]
ping

**Comment by dfm** [comment]
Hey! Thanks for your patience. I did [merge this into the develop branch about a week ago](https://github.com/dfm/emcee/commit/b709347baa82d45eadde0ab91240af36c0f24686), but I'm still working on the next release. Thanks!

**Pull request merged**
